
experiment: "gat-lstm"
name: "lstm"
description: "Two-layer GAT with LSTM layer at the end for seizure prediction, using correlation graph."
task: "seizure_prediction"

# Data (same splits as before)
datasets:
-
  set: "train"
  val_size: 0.2
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  sampling: True
  size: 1
  graph: 
      type: "correlation"
  edge_threshold: 0.4
  shuffle: True
  num_workers: 4

-
  set: "val"
  val_size: 0.2
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  graph: 
      type: "correlation"
  edge_threshold: 0.4
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "/home/ogut/data/test"
  batch_size: 32
  tfm: "fft"
  graph: 
      type: "correlation"
  edge_threshold: 0.4
  shuffle: False
  num_workers: 4

# Model
model:
  name: "LSTMGAT"
  n_epochs: 50
  optimizer: "Adam"
  use_scheduler: False
  learning_rate: 0.001
  criterion: "BCEWithLogitsLoss"
  config:
    in_channels:  # number of features per node (e.g. timepoints after FFT)
      354 
    hidden_channels_gat: 64

    hidden_channels_lstm: 128