---
experiment: "resnet"
name: "basic_resnet"
description: "Basic ResNet model for signal classification"
task: "v1"

# Data
datasets:
-
  set: "train"
  split: [0, 0.8]
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  shuffle: True
  num_workers: 4

-
  set: "val"
  split: [0.8, 1]
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "/home/ogut/data/test"
  batch_size: 32
  tfm: "fft"
  shuffle: False
  num_workers: 4

# Model
model:
  name : "ResNet"
  n_epochs: 50
  optimizer: "SGD"
  use_scheduler: True
  learning_rate: 0.001
  criterion: "BCEWithLogitsLoss"
  config:
    input_shape: 19
    output_shape: 1