---
experiment: "cnn"
name: "basic_cnn"
description: "Basic CNN model for signal classification"
task: "v1"

# Model
model:
  name : "CnnBase"
  n_epochs: 10
  optimizer: "SGD"
  use_scheduler: True
  learning_rate: 0.01
  criterion: "BCEWithLogitsLoss"
  config:
    input_shape: 19
    output_shape: 1
    kernel_size: 5

# Data
datasets:
-
  set: "train"
  split: [0, 0.8]
  path: "project/data/train"
  batch_size: 32
  tfm: "fft"
  shuffle: True
  num_workers: 4

-
  set: "val"
  split: [0.8, 1]
  path: "project/data/train"
  batch_size: 32
  tfm: "fft"
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "project/data/test"
  batch_size: 32
  tfm: "fft"
  shuffle: False
  num_workers: 4