---
experiment: "cnn"
name: "cnn_base_downsample"
description: "CNN with no tfm and downsampled"
task: "v1"

# Data
config_dataset:
  n_splits: 5
  tfm: ""
  num_workers: 4
  batch_size: 32

datasets:
-
  set: "train"
  path: "project/data/train"
  sampling: True
  size: 1
  shuffle: True

-
  set: "val"
  path: "project/data/train"
  shuffle: False

-
  set: "test"
  path: "project/data/test"
  shuffle: False

# Model
model:
  name : "CNN"
  n_epochs: 50
  optimizer: "Adam"
  use_scheduler: True
  learning_rate: 2e-4
  criterion: "BCEWithLogitsLoss"
  config:
    input_shape: [19,3000]