---
experiment: "cnn"
name: "cnn_clean_func_ds"
description: "CNN with cleaning function on inputs"
task: "v1"

# Data
datasets:
-
  set: "train"
  val_size: 0.2
  path: "project/data/train"
  batch_size: 32
  tfm: "clean"
  sampling: True
  size: 1
  shuffle: True
  num_workers: 4

-
  set: "val"
  val_size: 0.2
  path: "project/data/train"
  batch_size: 32
  tfm: "clean"
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "project/data/test"
  batch_size: 32
  tfm: "clean"
  shuffle: False
  num_workers: 4

# Model
model:
  name : "CNN"
  n_epochs: 50
  optimizer: "Adam"
  use_scheduler: True
  learning_rate: 1e-2
  criterion: "BCEWithLogitsLoss"
  config:
    input_shape: [19,3000]