---
experiment: "cnn"
name: "cnn_clean_func"
description: "CNN with cleaning function on inputs"
task: "v1"

# Data
datasets:
-
  set: "train"
  split: [0, 0.8]
  path: "project/data/train"
  batch_size: 32
  tfm: "clean"
  shuffle: True
  num_workers: 4

-
  set: "val"
  split: [0.8, 1]
  path: "project/data/train"
  batch_size: 32
  tfm: "clean"
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "project/data/test"
  batch_size: 32
  tfm: "clean"
  shuffle: False
  num_workers: 4

# Model
model:
  name : "CNN"
  n_epochs: 50
  optimizer: "SGD"
  use_scheduler: True
  learning_rate: 1e-2
  criterion: "BCEWithLogitsLoss"
  config:
    input_shape: [19,3000]