---
experiment: "cnn"
name: "cnn_clean_func"
description: "CNN with cleaning function on inputs"
task: "v1"

# Data
config_dataset:
  val_size: 0.2
  tfm: "clean"
  num_workers: 4
  batch_size: 32

datasets:
-
  set: "train"
  path: "project/data/train"
  sampling: True
  size: 1
  shuffle: True

-
  set: "val"
  path: "project/data/train"
  shuffle: False

-
  set: "test"
  path: "project/data/test"
  shuffle: False

# Model
model:
  name : "CNN"
  n_epochs: 50
  optimizer: "Adam"
  use_scheduler: True
  learning_rate: 1e-2
  criterion: "BCEWithLogitsLoss"
  config:
    input_shape: [19,3000]