# project/config/exp/graph/basic_gcn.yml
experiment: "gnn"
name: "basic_gcn"
description: "Two-layer GCN for seizure prediction"
task: "v1"

# Data (same splits as before)
datasets:
-
  set: "train"
  split: [0, 0.8]
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  graph: 
      type: "distance"
      path: "project/data/distances_3d.csv"
  edge_threshold: 0.5
  shuffle: True
  num_workers: 4

-
  set: "val"
  split: [0.8, 1]
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  graph: 
      type: "distance"
      path: "project/data/distances_3d.csv"
  edge_threshold: 0.5
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "/home/ogut/data/test"
  batch_size: 32
  tfm: "fft"
  edge_threshold: 0.5
  graph: 
    type: "distance"
    path: "project/data/distances_3d.csv"
  edge_threshold: 1
  shuffle: False
  num_workers: 4

# Model
model:
  name: "GCN"
  n_epochs: 20
  optimizer: "Adam"
  use_scheduler: False
  learning_rate: 0.001
  criterion: "BCEWithLogitsLoss"
  config:
    in_channels:  # number of features per node (e.g. timepoints after FFT)
      354
    hidden_channels: 64
    # edge_index will be passed in code (fixed electrode graph)
