# project/config/exp/graph/basic_gcn.yml
experiment: "gnn"
name: "basic_gcn"
description: "Two-layer GCN for seizure prediction, using correlation graph in time domain."
task: "seizure_prediction"

# Data (same splits as before)
datasets:
-
  set: "train"
  val_size: 0.2
  path: "project/data/train"
  batch_size: 32
  tfm: "clean"
  sampling: True
  size: 1
  graph: 
      type: "correlation"
  edge_threshold: 0.5
  shuffle: True
  num_workers: 4

-
  set: "val"
  val_size: 0.2
  path: "project/data/train"
  batch_size: 32
  tfm: "clean"
  graph: 
      type: "correlation"
  edge_threshold: 0.5
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "project/data/test"
  batch_size: 32
  tfm: "clean"
  edge_threshold: 0.5
  graph: 
      type: "correlation"
  edge_threshold: 0.5
  shuffle: False
  num_workers: 4

# Model
model:
  name: "GCN"
  n_epochs: 50
  optimizer: "Adam"
  use_scheduler: False
  learning_rate: 0.001
  criterion: "BCEWithLogitsLoss"
  config:
    in_channels:  # number of features per node (e.g. timepoints after FFT)
      3000
    hidden_channels: 64
    # edge_index will be passed in code (fixed electrode graph)
