# project/config/exp/graph/basic_gcn.yml
experiment: "gnn"
name: "gcn_dist_fft"
description: "Two-layer GCN for seizure prediction with distance graph in frequency domain."
task: "threshold_08"
# Data (same splits as before)
config_dataset:
  n_splits: 5
  tfm: "fft"
  graph: 
      type: "distance"
      path: "./project/data/distances_3d.csv"
      # path: "$HOME/EE452-Network-Machine-Learning/project/data/distances_3d.csv"
      edge_threshold: 0.5
  num_workers: 4
  batch_size: 32

datasets:
-
  set: "train"
  path: "project/data/train"
  # path: "/home/ogut/data/train"
  sampling: True
  size: 1
  shuffle: True

-
  set: "val"
  path: "project/data/train"
  # path: "/home/ogut/data/train"
  shuffle: False

-
  set: "test"
  path: "project/data/test"
  # path: "/home/ogut/data/train"
  shuffle: False

# Model
model:
  name: "GCN"
  n_epochs: 50
  optimizer: "Adam"
  use_scheduler: False
  learning_rate: 1e-4
  criterion: "BCEWithLogitsLoss"
  config:
    in_channels:  # number of features per node (e.g. timepoints after FFT)
      354 
    hidden_channels: 64
    # edge_index will be passed in code (fixed electrode graph)
