# project/config/exp/graph/basic_gcn.yml
experiment: "gnn"
name: "gcn_coherence_band_energies"
description: "Two-layer GCN for seizure prediction, using correlation graph."
task: "seizure_prediction"




# Data (same splits as before)
config_dataset:
  val_size: 0.2
  tfm: "time_filtering"
  graph:
      type: "coherence_band_energies"
      edge_threshold: 0.5
  num_workers: 4
  batch_size: 32

datasets:
-
  set: "train"
  path: "data/train"
  sampling: True
  size: 1
  shuffle: True

-
  set: "val"
  path: "data/train"
  shuffle: False

-
  set: "test"
  path: "data/test"
  shuffle: False

# Model
model:
  name: "GCN"
  n_epochs: 50
  optimizer: "Adam"
  use_scheduler: False
  learning_rate: 0.0001
  criterion: "BCEWithLogitsLoss"
  config:
    in_channels:  # number of features per node (e.g. timepoints after FFT)
      30
    hidden_channels: 10
    # edge_index will be passed in code (fixed electrode graph)
