# project/config/exp/graph/basic_gcn.yml
experiment: "gnn"
name: "gcn_corr_fft"
description: "Two-layer GCN for seizure prediction, using correlation graph."
task: "dropout_rm"

# Data (same splits as before)
config_dataset:
  val_size: 0.2
  tfm: "fft"
  graph: 
      type: "correlation"
      edge_threshold: 0.8
  num_workers: 4
  batch_size: 64

datasets:
-
  set: "train"
  path: "project/data/train"
  sampling: True
  size: 1
  shuffle: True

-
  set: "val"
  path: "project/data/train"
  shuffle: False

-
  set: "test"
  path: "project/data/test"
  shuffle: False

# Model
model:
  name: "GCN"
  n_epochs: 20
  optimizer: "Adam"
  use_scheduler: True
  learning_rate: 1e-4
  criterion: "BCEWithLogitsLoss"
  config:
    in_channels:  # number of features per node (e.g. timepoints after FFT)
      354 
    hidden_channels: 64
    # edge_index will be passed in code (fixed electrode graph)
