#!/bin/bash

#SBATCH --account=ee-452
#SBATCH --qos=ee-452
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=16G
#SBATCH --output run-log-%J.out

CFG=$1
SEED=$2

module load gcc python

source $HOME/venvs/venv_project/bin/activate

CMD="python3 $HOME/EE452-Network-Machine-Learning/project/src/run.py"

if [ -n "$CFG" ]; then
    CMD="$CMD --cfg $CFG"
fi

if [ -n "$SEED" ]; then
    CMD="$CMD --seed $SEED"
fi

eval $CMD