---
experiment: "resnet"
name: "basic_resnet"
description: "Basic ResNet model for signal classification"
task: "v1"

config_dataset:
  val_size: 0.2
  tfm: "fft"
  num_workers: 4
  batch_size: 32

datasets:
-
  set: "train"
  path: "/home/ogut/data/train"
  sampling: True
  size: 1
  shuffle: True

-
  set: "val"
  path: "/home/ogut/data/train"
  shuffle: False

-
  set: "test"
  path: "/home/ogut/data/test"
  shuffle: False

# Model
model:
  name : "ResNet"
  n_epochs: 50
  optimizer: "SGD"
  use_scheduler: True
  learning_rate: 0.001
  criterion: "BCEWithLogitsLoss"
  config:
    input_shape: 19
    output_shape: 1