---
experiment: "cnn"
name: "basic_cnn"
description: "Basic CNN model for signal classification"
task: "v1"

# Data
datasets:
-
  set: "train"
  split: [0, 0.8]
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  G_construction: "none"
  shuffle: True
  num_workers: 4

-
  set: "val"
  split: [0.8, 1]
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  G_construction: "none"
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "/home/ogut/data/test"
  batch_size: 32
  tfm: "fft"
  G_construction: "none"
  shuffle: False
  num_workers: 4

# Model
model:
  name : "CnnBase"
  n_epochs: 10
  optimizer: "SGD"
  use_scheduler: True
  learning_rate: 0.01
  criterion: "BCEWithLogitsLoss"
  config:
    layers: 
      - out_channels_multiplier: 2
        pooling: "max"
      - out_channels_multiplier: 4
        pooling: "max"
      - out_channels_multiplier: 8
        pooling: "max"
      - out_channels_multiplier: 16
        pooling: "adaptiveavg"
    input_shape: 19
    output_shape: 1
    kernel_size: 5