# project/config/exp/graph/basic_gat.yml
experiment: "gnn"
name: "basic_gat"
description: "Two-layer GATv2 for seizure prediction"
task: "v1"


# Data
datasets:
-
  set: "train"
  split: [0, 0.8]
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  graph: 
    type: "distance"
    path: "project/data/distances_3d.csv"

  edge_threshold: 1
  shuffle: True
  num_workers: 4

-
  set: "val"
  split: [0.8, 1]
  path: "/home/ogut/data/train"
  batch_size: 32
  tfm: "fft"
  graph: 
    type: "distance"
    path: "project/data/distances_3d.csv"
  edge_threshold: 1
  shuffle: False
  num_workers: 4

-
  set: "test"
  path: "/home/ogut/data/test"
  batch_size: 32
  tfm: "fft"
  graph: 
    type: "distance"
    path: "project/data/distances_3d.csv"
  edge_threshold: 1
  shuffle: False
  num_workers: 4

# Model
model:
  name: "GAT"
  n_epochs: 20
  optimizer: "Adam"
  use_scheduler: False
  learning_rate: 0.001
  criterion: "BCEWithLogitsLoss"
  config:
    in_channels:  # number of features per node
      128
    hidden_channels: 64
    # attention heads, dropout, etc., can be added here 
    heads: 4
