---
experiment: "fcn"
name: "fcn_fft"
description: "FCN with FFT transformation"
task: "v1"

# Data
config_dataset:
  n_splits: 5
  tfm: "fft"
  num_workers: 4
  batch_size: 128

datasets:
-
  set: "train"
  path: "project/data/train"
  sampling: True
  size: 1
  shuffle: True

-
  set: "val"
  path: "project/data/train"
  shuffle: False

-
  set: "test"
  path: "project/data/test"
  shuffle: False

# Model
model:
  name : "FCN"
  n_epochs: 10
  optimizer: "Adam"
  use_scheduler: True
  learning_rate: 2e-5
  criterion: "BCEWithLogitsLoss"
  config:
    input_channels: 19
    num_classes: 1